### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by FlaviusBejan** [Sirosky/AniTag#1]
Hello,

I've extracted both versions (1.0 & 1.1.0) and just run the app, but the UI looks like it's missing data. I've added a snipping to show what's going on.
![image](https://user-images.githubusercontent.com/8842356/76093862-5c9c4880-5fca-11ea-882b-b48d1bc80657.png)

This is the debug data from CMD:
> Godot` Engine v3.2.stable.official - https://godotengine.org
> OpenGL ES 3.0 Renderer: Radeon (TM) RX 480 Graphics
> parse successful: res://settings/settings.json
> File not found, cannot load database

Version 1.1.0 doesn't have the "File not found, cannot load database" message.

**Comment by Sirosky** [comment]
Hmm two questions

1. Have you tried creating a new library or loading an existing one? Also can you post the contents of settings.json?
2. What is your screen resolution?

**Comment by FlaviusBejan** [comment]
The screen resolution is 2560 x 1440 and the content on settings.json is: {"General":{"main_path":"user://db/Main.json","tags_hidden":[]}}
I can't add any content because I don't see any buttons. In the screenshot you can see that the app in in portrait mode.
![image](https://user-images.githubusercontent.com/8842356/76124442-55ddf780-6003-11ea-9c6f-7b2819a0c7dd.png)

**Comment by Sirosky** [comment]
Oof that doesn't look too good. The program was designed for 1920x1080 as I don't have access to devices with other resolutions. I've tried testing on lower resolutions but not higher as I don't have any 1440 or 4k screens =/ Also hadn't accounted for portrait mode.

I'm in the process of making a settings menu and I'm looking into scaling for different resolutions. In the meantime, [try this version](https://drive.google.com/open?id=1v7c167oBwlrC05PxrIaPTBmDK3yoEss1). It'll default to a resizable window which should work out better.

As a sidenote, do you have any experience with Godot?

**Comment by Sirosky** [comment]
Actually, try downloading 1.1.1. Don't bother with the version I uploaded the previous comment.

https://github.com/Sirosky/AniTag/releases/tag/1.1.1-beta

**Comment by FlaviusBejan** [comment]
I can confirm that now it works, but only with Fullscreen: off.
As it's in the archive, it still opens as it did in the previous versions, so I put the display in landscape, went to settings and changed to fullscreen: off, closed the app, put back in protrait mode, open it and it works.
It has the Windows border, which now allows the use of WindowKey + ArrowKeys to change the position on screen.
Using the same settings.json on v 1.1.0 doesn't work and changing back to fullscreen: on, while portrait mode is on, it goes back to the problem.
I don't have any experience with Godot, but I'm willing to help you test.

**Comment by Sirosky** [comment]
Yeah I implemented a window resizing script in 1.1.1, so it should play better now.

So to clarify, with 1.1.1, what doesn't work? And are you going to be running AniTag in portrait mode or landscape mode?

**Comment by FlaviusBejan** [comment]
If "fullscreen":true (in settings.json) it looks like the first picture in the first reply.
If "fullscreen":false it looks as on the Wiki page, but with the Windows border: 
![image](https://user-images.githubusercontent.com/8842356/76152439-54c2ce00-60c8-11ea-9a68-023f1f755eee.png)
I am going to run the app on the landscape monitor. I don't plan to use it on the portrait monitor.
In case you're curious I've put it on the portrait monitor and it looks fine. There is a small width bar on the bottom part that allows you to see the cover image or the options on the right side: 
![image](https://user-images.githubusercontent.com/8842356/76152505-ecc0b780-60c8-11ea-89f6-98debc692466.png)

**Comment by Sirosky** [comment]
Hmm very odd that the fullscreen mode isn't scaling up to the entire size of the monitor. Looks like windowed mode is mostly fine. As my most high-def display is still only 1080p there's not much I can do on my end. However, you can try compiling AniTag yourself-- it's very easy. Would you be interested in giving it a shot?

**Comment by FlaviusBejan** [comment]
It scales to full screen 😄 I made the app smaller so you can see how the windows borders look. 
![image](https://user-images.githubusercontent.com/8842356/76157789-924e4800-6116-11ea-855b-5c3565391d35.png)
I don't see a point on compiling it myself since v 1.1.1 fixes the problem that I've addressed. The fix is to change "fullscreen" to false in settings/settings.json (in case somebody else has the same problem). This way the user doesn't need to disconnect the display, or change the display settings to do the modifications inside the app.
I think that's best for you to leave fullscreen to true because it looks better.
Thank you for fixing this 😄

**Comment by Sirosky** [comment]
Awesome, glad it works!
