### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jtrpc** [Sirosky/AniTag#2]
https://drive.google.com/file/d/1YZvh0BKz-QgK2ZPxfR9E3SYOZysy1yq_/view?usp=sharing

What is this problem?

**Comment by Sirosky** [comment]
This happens when there's a potential API ban from AniDB. It's very unlikely though-- never encountered this issue myself. Which anime were you trying to update? And how large is your library?

**Comment by jtrpc** [comment]
Solved
